version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci

  pre_build:
    commands:
      - echo "Linting..."
      - npm run lint

  build:
    commands:
      - echo "Building..."
      - npm run build

artifacts:
  files:
    - '**/*'
  exclude-paths:
    - 'node_modules/**/*'

cache:
  paths:
    - 'node_modules/**/*'
    - '.next/cache/**/*'
